# Generated by Django 5.0.1 on 2024-01-22 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('deadlime', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 15, 47, 3, 875922))),
            ],
        ),
    ]
